language: cpp


compiler:  
    - gcc-7

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

before_install:
    - export CC=gcc-7
    - export CXX=g++-7



install:
    - wget -O boost_1_66_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.66.0/boost_1_66_0.tar.gz/download
    - tar xzf boost_1_66_0.tar.gz
    - cd boost_1_66_0/
    - ./bootstrap.sh
    - ./b2 headers
    - sudo cp -r boost /usr/local/include
    - cd ..

before_script:  
    - mkdir build
    - cd build
    - cmake ..
    - export CC=/usr/bin/gcc-7
    - export CXX=/usr/bin/g++-7
    # Check versions of gcc, g++ and cmake
    - gcc-7 -v && g++-7 -v && cmake --version


script:
    - make VERBOSE=1
    - make test

